/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RayCasting_CameraRenderNative */

#ifndef _Included_RayCasting_CameraRenderNative
#define _Included_RayCasting_CameraRenderNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RayCasting_CameraRenderNative
 * Method:    render
 * Signature: (II[I[DDDDDDLGame/Level;II)V
 */
JNIEXPORT void JNICALL Java_RayCasting_CameraRenderNative_render
  (JNIEnv *, jclass, jint, jint, jintArray, jdoubleArray, jdouble, jdouble, jdouble, jdouble, jdouble, jobject, jint, jint);

/*
 * Class:     RayCasting_CameraRenderNative
 * Method:    getColor
 * Signature: (DDIIIFDDFDDF)I
 */
JNIEXPORT jint JNICALL Java_RayCasting_CameraRenderNative_getColor
  (JNIEnv *, jclass, jdouble, jdouble, jint, jint, jint, jfloat, jdouble, jdouble, jfloat, jdouble, jdouble, jfloat);

#ifdef __cplusplus
}
#endif
#endif
